baseURL = "https://manateam.org"
languageCode = "en-us"
title = "Manateam"
theme = "vanilla-bootstrap-hugo-theme"

[menu]
  [[menu.nav]]
    name = "Home"
    pre = "home"
    url = "/"
    weight = 1
  [[menu.nav]]
    name = "Games"
    pre = "box"
    url = "/games/"
    weight = 2
  [[menu.nav]]
    name = "Contact"
    pre = "message-circle"
    url = "/contact"
    weight = 3

[params]
  includeBootstrapJs = false
  showActiveNav = true
  containerMaxWidth = "700px"
  dateFormat = "Jan 2, 2006"
  hideFooter = true
